// <auto-generated />
namespace FoodBack_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Alteraçõesestruturaisparaosrelacionamentos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alteraçõesestruturaisparaosrelacionamentos));
        
        string IMigrationMetadata.Id
        {
            get { return "201812032331351_Alterações estruturais para os relacionamentos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
